#!/bin/sh
# Automatically remap wacom devices when switching monitors in i3.
#
# Usage:
# i3-map-wacom-to-monitor [device] [device] [...]
#
# It is recommended that you put something like this in your .i3/config:
# exec --no-startup-id "i3-map-device-to-monitor 'Wacom Intuos PT S 2 Pen stylus' 'Wacom Intuos PT S 2 Finger touch"

run() {
	# Get the name of the focused monitor
	output="$(echo "$json"|jq --raw-output '.["current"]["output"]')"
	# Run wacom-aspect for all given devices
	wacom-aspect "$output" "${@}"
}

run "${@}"
i3-msg -t subscribe -m '[ "workspace" ]' \
|while read -r json; do
	run "${@}"
done
